name: storesalephone
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  readmore: ^3.0.0
  line_icons: ^2.0.3
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  intl: ^0.17.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  image_picker: ^1.1.1
  cloudinary_public: ^0.23.1
  flutter_dotenv: ^5.1.0
  number_paginator: ^0.4.1
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  flutter_speed_dial: ^7.0.0
  sqflite: ^2.3.3+1
  introduction_screen: ^3.1.14
  cached_network_image: ^3.3.1
  line_awesome_flutter: ^3.0.1
  toastification: ^2.0.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/test.json
    - assets/carousel/
    - .env

